// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CrawledUrl is the predicate function for crawledurl builders.
type CrawledUrl func(*sql.Selector)

// LinkUrl is the predicate function for linkurl builders.
type LinkUrl func(*sql.Selector)
