// Code generated by ent, DO NOT EDIT.

package ent

import (
	"JY8752/crawling_app_batch/ent/crawledurl"
	"JY8752/crawling_app_batch/ent/linkurl"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CrawledUrlCreate is the builder for creating a CrawledUrl entity.
type CrawledUrlCreate struct {
	config
	mutation *CrawledUrlMutation
	hooks    []Hook
}

// SetURL sets the "url" field.
func (cuc *CrawledUrlCreate) SetURL(s string) *CrawledUrlCreate {
	cuc.mutation.SetURL(s)
	return cuc
}

// SetCreatedAt sets the "created_at" field.
func (cuc *CrawledUrlCreate) SetCreatedAt(t time.Time) *CrawledUrlCreate {
	cuc.mutation.SetCreatedAt(t)
	return cuc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cuc *CrawledUrlCreate) SetNillableCreatedAt(t *time.Time) *CrawledUrlCreate {
	if t != nil {
		cuc.SetCreatedAt(*t)
	}
	return cuc
}

// SetUpdatedAt sets the "updated_at" field.
func (cuc *CrawledUrlCreate) SetUpdatedAt(t time.Time) *CrawledUrlCreate {
	cuc.mutation.SetUpdatedAt(t)
	return cuc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cuc *CrawledUrlCreate) SetNillableUpdatedAt(t *time.Time) *CrawledUrlCreate {
	if t != nil {
		cuc.SetUpdatedAt(*t)
	}
	return cuc
}

// AddLinkURLIDs adds the "link_urls" edge to the LinkUrl entity by IDs.
func (cuc *CrawledUrlCreate) AddLinkURLIDs(ids ...int) *CrawledUrlCreate {
	cuc.mutation.AddLinkURLIDs(ids...)
	return cuc
}

// AddLinkUrls adds the "link_urls" edges to the LinkUrl entity.
func (cuc *CrawledUrlCreate) AddLinkUrls(l ...*LinkUrl) *CrawledUrlCreate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return cuc.AddLinkURLIDs(ids...)
}

// Mutation returns the CrawledUrlMutation object of the builder.
func (cuc *CrawledUrlCreate) Mutation() *CrawledUrlMutation {
	return cuc.mutation
}

// Save creates the CrawledUrl in the database.
func (cuc *CrawledUrlCreate) Save(ctx context.Context) (*CrawledUrl, error) {
	var (
		err  error
		node *CrawledUrl
	)
	cuc.defaults()
	if len(cuc.hooks) == 0 {
		if err = cuc.check(); err != nil {
			return nil, err
		}
		node, err = cuc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CrawledUrlMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cuc.check(); err != nil {
				return nil, err
			}
			cuc.mutation = mutation
			if node, err = cuc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(cuc.hooks) - 1; i >= 0; i-- {
			if cuc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cuc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, cuc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*CrawledUrl)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from CrawledUrlMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cuc *CrawledUrlCreate) SaveX(ctx context.Context) *CrawledUrl {
	v, err := cuc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cuc *CrawledUrlCreate) Exec(ctx context.Context) error {
	_, err := cuc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuc *CrawledUrlCreate) ExecX(ctx context.Context) {
	if err := cuc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuc *CrawledUrlCreate) defaults() {
	if _, ok := cuc.mutation.CreatedAt(); !ok {
		v := crawledurl.DefaultCreatedAt
		cuc.mutation.SetCreatedAt(v)
	}
	if _, ok := cuc.mutation.UpdatedAt(); !ok {
		v := crawledurl.DefaultUpdatedAt
		cuc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuc *CrawledUrlCreate) check() error {
	if _, ok := cuc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "CrawledUrl.url"`)}
	}
	if v, ok := cuc.mutation.URL(); ok {
		if err := crawledurl.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "CrawledUrl.url": %w`, err)}
		}
	}
	if _, ok := cuc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CrawledUrl.created_at"`)}
	}
	if _, ok := cuc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CrawledUrl.updated_at"`)}
	}
	return nil
}

func (cuc *CrawledUrlCreate) sqlSave(ctx context.Context) (*CrawledUrl, error) {
	_node, _spec := cuc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cuc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (cuc *CrawledUrlCreate) createSpec() (*CrawledUrl, *sqlgraph.CreateSpec) {
	var (
		_node = &CrawledUrl{config: cuc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: crawledurl.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: crawledurl.FieldID,
			},
		}
	)
	if value, ok := cuc.mutation.URL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: crawledurl.FieldURL,
		})
		_node.URL = value
	}
	if value, ok := cuc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: crawledurl.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := cuc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: crawledurl.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if nodes := cuc.mutation.LinkUrlsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   crawledurl.LinkUrlsTable,
			Columns: crawledurl.LinkUrlsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: linkurl.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CrawledUrlCreateBulk is the builder for creating many CrawledUrl entities in bulk.
type CrawledUrlCreateBulk struct {
	config
	builders []*CrawledUrlCreate
}

// Save creates the CrawledUrl entities in the database.
func (cucb *CrawledUrlCreateBulk) Save(ctx context.Context) ([]*CrawledUrl, error) {
	specs := make([]*sqlgraph.CreateSpec, len(cucb.builders))
	nodes := make([]*CrawledUrl, len(cucb.builders))
	mutators := make([]Mutator, len(cucb.builders))
	for i := range cucb.builders {
		func(i int, root context.Context) {
			builder := cucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CrawledUrlMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cucb *CrawledUrlCreateBulk) SaveX(ctx context.Context) []*CrawledUrl {
	v, err := cucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cucb *CrawledUrlCreateBulk) Exec(ctx context.Context) error {
	_, err := cucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cucb *CrawledUrlCreateBulk) ExecX(ctx context.Context) {
	if err := cucb.Exec(ctx); err != nil {
		panic(err)
	}
}
