// Code generated by ent, DO NOT EDIT.

package ent

import (
	"JY8752/crawling_app_batch/ent/crawledurl"
	"JY8752/crawling_app_batch/ent/linkurl"
	"JY8752/crawling_app_batch/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	crawledurlFields := schema.CrawledUrl{}.Fields()
	_ = crawledurlFields
	// crawledurlDescURL is the schema descriptor for url field.
	crawledurlDescURL := crawledurlFields[0].Descriptor()
	// crawledurl.URLValidator is a validator for the "url" field. It is called by the builders before save.
	crawledurl.URLValidator = crawledurlDescURL.Validators[0].(func(string) error)
	// crawledurlDescCreatedAt is the schema descriptor for created_at field.
	crawledurlDescCreatedAt := crawledurlFields[1].Descriptor()
	// crawledurl.DefaultCreatedAt holds the default value on creation for the created_at field.
	crawledurl.DefaultCreatedAt = crawledurlDescCreatedAt.Default.(time.Time)
	// crawledurlDescUpdatedAt is the schema descriptor for updated_at field.
	crawledurlDescUpdatedAt := crawledurlFields[2].Descriptor()
	// crawledurl.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	crawledurl.DefaultUpdatedAt = crawledurlDescUpdatedAt.Default.(time.Time)
	linkurlFields := schema.LinkUrl{}.Fields()
	_ = linkurlFields
	// linkurlDescURL is the schema descriptor for url field.
	linkurlDescURL := linkurlFields[0].Descriptor()
	// linkurl.URLValidator is a validator for the "url" field. It is called by the builders before save.
	linkurl.URLValidator = linkurlDescURL.Validators[0].(func(string) error)
	// linkurlDescReferer is the schema descriptor for referer field.
	linkurlDescReferer := linkurlFields[1].Descriptor()
	// linkurl.RefererValidator is a validator for the "referer" field. It is called by the builders before save.
	linkurl.RefererValidator = linkurlDescReferer.Validators[0].(func(string) error)
	// linkurlDescCreatedAt is the schema descriptor for created_at field.
	linkurlDescCreatedAt := linkurlFields[2].Descriptor()
	// linkurl.DefaultCreatedAt holds the default value on creation for the created_at field.
	linkurl.DefaultCreatedAt = linkurlDescCreatedAt.Default.(time.Time)
	// linkurlDescUpdatedAt is the schema descriptor for updated_at field.
	linkurlDescUpdatedAt := linkurlFields[3].Descriptor()
	// linkurl.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	linkurl.DefaultUpdatedAt = linkurlDescUpdatedAt.Default.(time.Time)
}
